version: '3'

volumes:
  app-postgres-data:
    driver: local

services:
  app:
    image: node:20-alpine
    volumes:
      - ./front:/app
    command: npm run dev
    working_dir: /app
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development

  api:
    container_name: artia-api
    image: webdevops/php-nginx:8.1-alpine
    volumes:
      - ./back:/app
    ports:
      - 81:80
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_MEMORY_LIMIT=256M
      - php.opcache.enable_cli=1

  postgres:
    image: postgres:15-alpine
    volumes:
      - app-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
