#!/bin/bash

export USER_UID=$UID

handle_command() {
  if [[ $1 == "start" ]]; then
    start_environment
  fi

  if [[ $1 == "stop" ]]; then
    stop_environment
  fi

  if [[ $1 == "clean" ]]; then
    clean_environment
  fi

  if [[ $1 == "tinker" ]]; then
    start_tinker
  fi

  if [[ $1 == "setup" ]]; then
      setup_environment
    fi

  print_manual
}

print_manual() {
  echo "Laravel Docker - by Guilherme Matoso"
  echo ""
  echo "Available arguments:"
  echo -e "\e[32mstart\e[39m\tStarts the environment"
  echo -e "\e[32mstop\e[39m\tStops the environment"
  echo -e "\e[32mclean\e[39m\tDown the environment, clean orphans and remove network."
}

setup_environment() {
  echo -e "[\e[33mWAIT\e[39m] Starting environment"
  docker compose stop
  docker compose build
  docker compose run app npm install
  docker compose run -u root app chown -R $USER_UID:$USER_UID /app
  docker compose up -d --remove-orphans

  docker compose exec api cp .env.example .env
  docker compose exec api composer install
  docker compose exec api php artisan migrate:fresh --seed
  docker compose exec api php artisan key:generate
  docker compose exec api php artisan storage:link
  docker compose exec -u root api chmod -R 777 /app/storage

  if [ $? -eq 0 ]; then
    echo -e "[\e[32mOK\e[39m] Environment started"
  else
    echo -e "[\e[31mFAIL\e[39m] Fail on starting environment."
    stop_environment
  fi

  exit
}

start_environment() {
  echo -e "[\e[33mWAIT\e[39m] Starting environment"
  docker compose stop
  docker compose run -u root app chown -R $USER_UID:$USER_UID /app
  docker compose up -d --remove-orphans

  if [ $? -eq 0 ]; then
    echo -e "[\e[32mOK\e[39m] Environment started"
  else
    echo -e "[\e[31mFAIL\e[39m] Fail on starting environment."
    stop_environment
  fi

  exit
}

stop_environment() {
  echo -e "[\e[33mWAIT\e[39m] Stopping environment"
  docker compose stop
  echo -e "[\e[32mOK\e[39m] Environment stopped"
  exit
}

start_tinker() {
  echo -e "[\e[33mWAIT\e[39m] Starting tinker"
  docker compose exec -u root api php artisan tinker
  echo -e "[\e[32mOK\e[39m] tinker started"
  exit
}

clean_environment() {
  echo -e "[\e[33mWAIT\e[39m] Cleaning environment"
  docker compose down --remove-orphans
  echo -e "[\e[32mOK\e[39m] Environment cleaned"
  exit
}

handle_command $1
